using OxyPlot;
using OxyPlot.Axes;
using OxyPlot.Series;

namespace GUI;

/// <summary>
/// Generate Oxyplot <see cref="PlotModel"/>s based on plot tables generated by <see cref="Interpreter"/>.
/// </summary>
public static class PlotController
{
    /// <summary>
    /// Plot each line individually and generate an interference pattern.
    /// </summary>
    /// <param name="lines"></param>
    /// <param name="minimumX"></param>
    /// <param name="maximumX"></param>
    /// <param name="xStep"></param>
    public static PlotModel InterferencePlot(
        double[][] lines,
        double minimumX,
        double maximumX,
        double xStep)
    {
        PlotModel model = CreatePlotModel(minimumX, maximumX);
        if (lines.Length == 0)
            return model;
        
        double[] interferencePattern = new double[lines[0].Length];

        // Plot individual lines.
        for (int i = 0; i < lines.Length; i++)
        {
            LineSeries individualSeries = new LineSeries 
            { 
                Color = OxyColor.FromArgb(80, 100, 100, 255),
                StrokeThickness = 1,
                Title = $"Line {i}"
            };
        
            double x = maximumX;
            for (int j = 0; j < lines[i].Length; j++)
            {
                individualSeries.Points.Add(new DataPoint(x, lines[i][j]));
                interferencePattern[j] += lines[i][j]; // Accumulate for interference.
                x -= xStep;
            }
        
            model.Series.Add(individualSeries);
        }

        // Plot interference pattern.
        LineSeries interferenceSeries = new LineSeries 
        { 
            Color = OxyColor.FromRgb(255, 0, 0),
            StrokeThickness = 3,
            Title = "Interference Pattern"
        };
    
        double xFinal = maximumX;
        for (int j = 0; j < lines[0].Length; j++)
        {
            interferenceSeries.Points.Add(new DataPoint(xFinal, interferencePattern[j]));
            xFinal -= xStep;
        }

        model.Series.Add(interferenceSeries);
        return model;
    }    

    /// <summary>
    /// Plot each line individually.
    /// </summary>
    /// <param name="lines"></param>
    /// <param name="minimumX"></param>
    /// <param name="maximumX"></param>
    /// <param name="xStep"></param>
    /// <returns></returns>
    public static PlotModel IndividualPlot(
        double[][] lines,
        double minimumX,
        double maximumX,
        double xStep)
    {
        PlotModel model = CreatePlotModel(minimumX, maximumX);
        if (lines.Length == 0)
            return model;
        
        for (int i =  0; i < lines.Length; i++)
        {
            var lineSeries = new LineSeries()
            {
                Title = $"Line {i}"
            };
            double x = maximumX;
            foreach (double y in lines[i])
            {
                x -= xStep;
                lineSeries.Points.Add(new DataPoint(x, y));
            }
            model.Series.Add(lineSeries);
        }

        return model;
    }
    
    /// <summary>
    /// Create the Oxyplot graph model.
    /// </summary>
    /// <param name="minimumX"></param>
    /// <param name="maximumX"></param>
    /// <returns>The plot model.</returns>
    private static PlotModel CreatePlotModel(double minimumX, double maximumX)
    {
        var model = new PlotModel();
        model.Axes.Add(new LinearAxis
        {
            Position = AxisPosition.Bottom,
            Minimum = minimumX,
            Maximum = maximumX,
            Title = "X",
            AxislineStyle = LineStyle.Solid,
            AxislineThickness = 2,
            MajorGridlineStyle = LineStyle.Solid,
            MinorGridlineStyle = LineStyle.Dot,
            MajorGridlineColor = OxyColor.FromRgb(200, 200, 200),
            MinorGridlineColor = OxyColor.FromRgb(230, 230, 230)
        });

        model.Axes.Add(new LinearAxis
        {
            Position = AxisPosition.Left,
            Title = "Y",
            Minimum = minimumX,
            Maximum = maximumX,
            AxislineStyle = LineStyle.Solid,
            AxislineThickness = 2,
            MajorGridlineStyle = LineStyle.Solid,
            MinorGridlineStyle = LineStyle.Dot,
            MajorGridlineColor = OxyColor.FromRgb(200, 200, 200),
            MinorGridlineColor = OxyColor.FromRgb(230, 230, 230)
        });
        return model;
    }
}